<?php

namespace DP\VoipServer\VoipServerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VoipServerInstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoipServerInstanceRepository extends EntityRepository
{
}
