<?php

namespace DP\Core\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    public function getAvailableGames()
    {
        $qb = $this->createQueryBuilder('game');
        $qb->select('game.id, game.name')->where('game.available = true');
        
        return $qb->getQuery()->getResult();
    }
    
    public function getAvailableSteamGames() {
        return $this->getQBAvailableSteamGames()->getQuery()->getResult();
    }
    
    public function getQBAvailableSteamGames() {
        $qb = $this->createQueryBuilder('game');
        $expr = $qb->expr();
        
        $qb->where($expr->orX(
                    $expr->eq('game.bin', '?1'), 
                    $expr->eq('game.bin', '?2')
                  ))
            ->andWhere('game.available = true')
            ->setParameters(array(1 => 'hlds_run', 2 => 'srcds_run'));
        
        return $qb;
    }
}