<?php

/**
 * This file is part of Dedipanel project
 *
 * (c) 2010-2015 Dedipanel <http://www.dedicated-panel.net>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace DP\Core\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    public function getAvailableGames()
    {
        $qb = $this->createQueryBuilder('game');
        $qb->select('game.id, game.name')->where('game.available = true');
        
        return $qb->getQuery()->getResult();
    }
    
    public function getAvailableSteamGames()
    {
        return $this->getQBAvailableSteamGames()->getQuery()->getResult();
    }
    
    public function getQBAvailableSteamGames()
    {
        $qb = $this->createQueryBuilder('game');
        
        $qb
            ->where('game.type = ?1')
            ->andWhere('game.available = true')
            ->setParameters(array(1 => 'steam'));
        ;
        
        return $qb;
    }
    
    public function getAvailableMinecraftGames()
    {
        return $this->getQBAvailableMinecraftGames()->getQuery()->getResult();
    }
    
    public function getQBAvailableMinecraftGames()
    {
        $qb = $this->createQueryBuilder('game');
        
        $qb
            ->where('game.type = ?1')
            ->andWhere('game.available = true')
            ->setParameters(array(1 => 'minecraft'));
        ;
        
        return $qb;
    }
}