Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.network :private_network, ip: "10.0.0.200"
    config.ssh.forward_agent = true

  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--memory", 1024]
    v.customize ["modifyvm", :id, "--name", "dedipanel"]
  end

  nfs_setting = RUBY_PLATFORM =~ /darwin/ || RUBY_PLATFORM =~ /linux/
  
  config.vm.synced_folder "./../", "/var/www/dedipanel", id: "vagrant-root"
  config.vm.synced_folder "./../../PHPSeclibWrapperBundle", "/var/www/PHPSeclibWrapperBundle", id: "vagrant-root"
  config.vm.synced_folder "./../../dedipanel-site", "/var/www/dedipanel-site", id: "vagrant-root"

  config.vm.provision :shell do |shell|
    shell.path = "bootstrap.sh"
  end

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.options = ['--verbose']
  end
end
