Vagrant.configure("2") do |config|
  config.vm.hostname = "dedipanel.dev"
  config.vm.box = "ubuntu/trusty64"

  config.vm.network :private_network, ip: "10.0.0.200"
  config.ssh.forward_agent = true

  config.vm.provider :virtualbox do |v|
    v.memory = 2048
    v.cpus = 3
    v.name = "dedipanel"
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--cpuexecutioncap", "75"]
  end

  config.vm.synced_folder "./../../PHPSeclibWrapperBundle", "/var/www/PHPSeclibWrapperBundle"
  config.vm.synced_folder "./../../dedipanel-site", "/var/www/dedipanel-site"
  config.vm.synced_folder "./../", "/var/www/dedipanel"

  config.vm.provision :shell do |shell|
    shell.path = "bootstrap.sh"
  end

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.options = ['--verbose']
  end
end
