<?php

/**
 * BaseVm
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $ip
 * @property int $port
 * @property string $user
 * @property string $keyfile
 * @property Doctrine_Collection $GroupVms
 * @property Steam $Steam
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVm extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('vm');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('ip', 'string', 15, array(
             'type' => 'string',
             'ip' => true,
             'notnull' => true,
             'length' => '15',
             ));
        $this->hasColumn('port', 'int', 5, array(
             'type' => 'int',
             'notnull' => true,
             'length' => '5',
             ));
        $this->hasColumn('user', 'string', 16, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '16',
             ));
        $this->hasColumn('keyfile', 'string', 23, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '23',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('GroupVm as GroupVms', array(
             'local' => 'id',
             'foreign' => 'vm_id'));

        $this->hasOne('Steam', array(
             'local' => 'id',
             'foreign' => 'idVm'));
    }
}