<?php

/**
 * BaseSteam
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $idVm
 * @property int $port
 * @property integer $jeu
 * @property string $dir
 * @property int $maxplayers
 * @property bool $mm
 * @property bool $amx
 * @property bool $amxx
 * @property bool $mmsrc
 * @property bool $srcm
 * @property bool $es
 * @property Vm $Vm
 * @property Jeu $Jeu
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSteam extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('serveurs');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('idVm', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('port', 'int', 5, array(
             'type' => 'int',
             'notnull' => true,
             'length' => '5',
             ));
        $this->hasColumn('jeu', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('dir', 'string', 12, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '12',
             ));
        $this->hasColumn('maxplayers', 'int', 2, array(
             'type' => 'int',
             'notnull' => true,
             'length' => '2',
             ));
        $this->hasColumn('mm', 'bool', null, array(
             'type' => 'bool',
             'default' => 0,
             'notnull' => true,
             ));
        $this->hasColumn('amx', 'bool', null, array(
             'type' => 'bool',
             'default' => 0,
             'notnull' => true,
             ));
        $this->hasColumn('amxx', 'bool', null, array(
             'type' => 'bool',
             'default' => 0,
             'notnull' => true,
             ));
        $this->hasColumn('mmsrc', 'bool', null, array(
             'type' => 'bool',
             'default' => 0,
             'notnull' => true,
             ));
        $this->hasColumn('srcm', 'bool', null, array(
             'type' => 'bool',
             'default' => 0,
             'notnull' => true,
             ));
        $this->hasColumn('es', 'bool', null, array(
             'type' => 'bool',
             'default' => 0,
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Vm', array(
             'local' => 'idVm',
             'foreign' => 'id'));

        $this->hasOne('Jeu', array(
             'local' => 'jeu',
             'foreign' => 'id'));
    }
}