<?php

/**
 * BaseUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $pseudo
 * @property string $email
 * @property string $mdp
 * @property string $lang
 * @property Doctrine_Collection $Groups
 * @property Doctrine_Collection $GroupUsers
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUser extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('users');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('pseudo', 'string', 15, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '15',
             ));
        $this->hasColumn('email', 'string', 40, array(
             'type' => 'string',
             'email' => true,
             'notnull' => true,
             'length' => '40',
             ));
        $this->hasColumn('mdp', 'string', 40, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '40',
             ));
        $this->hasColumn('lang', 'string', 6, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'fr',
             'length' => '6',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Group as Groups', array(
             'refClass' => 'GroupUser',
             'local' => 'id',
             'foreign' => 'id'));

        $this->hasMany('GroupUser as GroupUsers', array(
             'local' => 'id',
             'foreign' => 'user_id'));
    }
}