<?php

/**
 * BaseGroupVm
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $group_id
 * @property integer $vm_id
 * @property bool $access
 * @property bool $admin
 * @property Group $Group
 * @property Vm $Vm
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGroupVm extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('groupvms');
        $this->hasColumn('group_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('vm_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('access', 'bool', null, array(
             'type' => 'bool',
             'default' => 0,
             'notnull' => true,
             ));
        $this->hasColumn('admin', 'bool', null, array(
             'type' => 'bool',
             'default' => 0,
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Group', array(
             'local' => 'group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Vm', array(
             'local' => 'vm_id',
             'foreign' => 'id'));
    }
}