<?php

/**
 * BaseJeu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nomJeu
 * @property string $installName
 * @property string $launchName
 * @property enum $bin
 * @property bool $source
 * @property bool $orangebox
 * @property string $map
 * @property bool $available
 * @property Doctrine_Collection $Steam
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJeu extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('jeux');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nomJeu', 'string', 24, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '24',
             ));
        $this->hasColumn('installName', 'string', 24, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '24',
             ));
        $this->hasColumn('launchName', 'string', 24, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '24',
             ));
        $this->hasColumn('bin', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'hlds_run',
              1 => 'srcds_run',
              2 => 'ucc-bin',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('source', 'bool', null, array(
             'type' => 'bool',
             'default' => 0,
             'notnull' => true,
             ));
        $this->hasColumn('orangebox', 'bool', null, array(
             'type' => 'bool',
             'default' => 0,
             'notnull' => true,
             ));
        $this->hasColumn('map', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '20',
             ));
        $this->hasColumn('available', 'bool', null, array(
             'type' => 'bool',
             'default' => 1,
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Steam', array(
             'local' => 'id',
             'foreign' => 'jeu'));
    }
}