<?php

/**
 * GroupRightTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GroupRightTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GroupRightTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GroupRight');
    }
}