<?php

/**
 * GroupVmTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GroupVmTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GroupVmTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GroupVm');
    }
}