<?php

/**
 * GroupMachinesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GroupMachinesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GroupMachinesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GroupMachines');
    }
}