<?php

/**
 * JeuTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JeuTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JeuTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Jeu');
    }
    
    public function getAvailableGames() {
        $q = Doctrine_Query::create()->select('id, nomJeu')->from('Jeu')->where('available = 1');
        $res = $q->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
        $q->free();
        
        return $res;
    }
}