<?php

/**
 * UserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('User');
    }
    
    public function isValidIdents($pseudo, $mdp) {
        $q = Doctrine_Query::create()
            ->from('User')
            ->where('pseudo = ?')
            ->andWhere('mdp = ?');
        $user = $q->fetchOne(array($pseudo, $mdp), Doctrine_Core::HYDRATE_ARRAY);
        $q->free();
        
        return $user;
    }
}