<?php

/**
 * UserGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserGroup');
    }
}