<?php

/**
 * UserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('User');
    }
    
    public function isValidIdents($pseudo, $mdp) {
        $q = Doctrine_Query::create()->select('id, pseudo, email, lang')->from('User')
            ->where('pseudo = ?')->andWhere('mdp = ?');
        $user = $q->fetchOne(array($pseudo, $mdp), Doctrine_Core::HYDRATE_ARRAY);
        $q->free();
        
        return $user;
    }
    
    // Vérifie l'utilisation d'un pseudo/mail
    public function existIdents($pseudo, $email) {
        $q = Doctrine_Query::create()->select('id')->from('User')
            ->where('pseudo = ?')->orWhere('email = ?');
        $exist = $q->fetchOne(array($pseudo, $email), Doctrine_Core::HYDRATE_ARRAY);
        $q->free();
        
        return $exist['id'];
    }
    
    public function modifyUser($uid, $pseudo, $email, $lang, $mdp = null) {
        $q = Doctrine_Query::create()
            ->update('User')
            ->set('pseudo', '?', $pseudo)
            ->set('email', '?', $email)
            ->set('lang', '?', $lang)
            ->where('id = ?', $uid);
        
        // On modifie le mdp si nécessaire
        if ($mdp != null) $q->set('mdp', 'SHA1(?)', $mdp);
        
        return $q->execute();
    }
    
    public function delete($uid) {
        $q = Doctrine_Query::create()->delete('User')->where('id = ?', $uid);
        return $q->execute();
    }

    public function getUser($uid) {
        $q = Doctrine_Query::create()->select('pseudo, email, lang')->from('User')
            ->where('id = ?', $uid);
        $res = $q->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
        $q->free();
        
        return $res[0];
    }
}