<?php

/**
 * VmTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VmTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VmTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Vm');
    }
    
    public function getVMs() {
        $q = Doctrine_Query::create()->select('ip, port, user')->from('Vm');
        $res = $q->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
        $q->free();
        
        return $res;
    }
    
    // Vérifie si une vm est déjà prise en charge selon son ip, port et user
    public function exists($ip, $port, $user) {
        $q = Doctrine_Query::create()->select('id')->from('Vm')
            ->where('ip = ?', $ip)->andWhere('port = ?', $port)->andWhere('user = ?', $user);
        $res = $q->fetchOne(array(), Doctrine_Core::HYDRATE_ARRAY);
        $q->free();
        
        return $res['id'];
    }
}