<?php

namespace DP\GameServer\MinecraftBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MinecraftServerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MinecraftServerRepository extends EntityRepository
{
}
