<?php

namespace DP\VoipServer\TeamspeakServerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TeamspeakServerInstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamspeakServerInstanceRepository extends EntityRepository
{
}
