<?php

namespace DP\GameServer\SteamServerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SteamServerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SteamServerRepository extends EntityRepository
{
}